### ISSUE TITLE
Use ch unit for line width

### ISSUE THREAD

**Issue by basham** [basham/v4.bash.am#35]
> According to several sources designers should strive for 45 to 85 characters per line since the ideal width for a paragraph is supposedly 65 characters.

> When defining widths of text blocks the ch unit may come in handy since 1ch is equivalent to the width of the zero (0) character. It also changes as the font-family or font-size changes.

```css
p {
  /* Maximum width of 65characters */
  max-width: 65ch;
}
```

https://medium.com/@matuzo/writing-css-with-accessibility-in-mind-8514a0007939
