### ISSUE TITLE
Update list style

### ISSUE THREAD

**Issue by basham** [basham/v4.bash.am#39]
https://betterwebtype.com/articles/2018/10/15/rhythm-in-web-typography/#hanging-punctuation-with-other-characters

```css
ul, ol {
  padding-left: 0;
  list-style-position: outside;
}
```
